### PR TITLE
fix bug where non-gifs don't import from disk

### PR DESCRIPTION
**Pull request by art0007i**
also some minor cleanup here and there

### CODE REVIEW

**Comment by astralchan** [comment]
I will pull and test things locally when I get back home.

**Comment by astralchan** [comment]
I reflected the changes in [c5e66af](https://github.com/astralchan/GifImporter/commit/c5e66af4c5413a97501f05797e14e79c7253e8c9).

**Comment by art0007i** [comment]
out of curiosity why not merge the pull?

**Comment by astralchan** [comment]
There were other changes I wanted to do, and on some lines you had spaces instead of tabs / etc.

**Pull request closed without merging**
